from nginx
run rm -rf /usr/share/nginx/html/index.html
run rm -rf /etc/nginx/nginx.conf
run rm -rf /etc/nginx/conf.d/default.conf
copy static /usr/share/nginx/html/
copy nginx.conf /etc/nginx/nginx.conf
